In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt

In [14]:
input_path = r"..\2_GLUE_prerun\results\LittleWashita-2023-08-26-determine-GW-params"
output_path = r".\results\LittleWashita-2023-08-26-determine-GW-params"
if not os.path.exists(output_path):
    os.makedirs(output_path)

In [15]:
evaluation_metrics = pd.read_csv(os.path.join(input_path, "evaluation_metrics.csv"))
evaluation_metrics.set_index(keys="run_id", inplace=True)
evaluation_metrics.head()

,NSE on Flow,NSE on Soil,KGE on Flow,KGE on Soil,SeasonTrans of Soil dry2wet_start,SeasonTrans of Soil dry2wet_end,SeasonTrans of Soil wet2dry_start,SeasonTrans of Soil wet2dry_end
run_id,,,,,,,,
0,-30.568738,-12.342179,-3.686758,-0.553540,72.749674,108.922218,66.649729,130.712276
1,-83.056301,-0.374212,-7.333551,0.160021,72.749565,115.994626,66.146897,161.431462
2,-70.208145,-3.862425,-6.695484,-0.018434,72.844123,113.131792,65.334942,141.854032
3,-15.989324,-1.395726,-2.430271,0.122937,72.749565,121.328924,65.628257,166.074534
4,-202.755735,0.009241,-12.687862,0.062920,95.348474,140.208906,51.937005,104.204529

In [16]:
parameters = pd.read_csv(os.path.join(input_path, "prior_parameters.csv"))
parameters.set_index(keys="run_id", inplace=True)
parameters.head()

,bb,satdk,satpsi,slop,smcmax,wltsmc,max_gw_storage,Cgw,epon,K_nash,refkdt,trigger_z_m,alpha_fc,K_lf
run_id,,,,,,,,,,,,,,
0,4.027623,0.000351,0.438172,0.057207,0.843931,0.137223,68.195614,1.527645,3.546989,0.822001,0.193795,0.477602,0.257059,0.653631
1,9.320904,0.000271,0.628929,0.254580,0.239038,0.085257,33.573071,6.585309,0.265659,0.977133,2.459490,0.603067,0.223187,0.455743
2,2.406037,0.000084,0.271769,0.196694,0.365838,0.019829,106.207128,8.361439,3.151870,0.598343,3.822082,0.444100,0.305219,0.790704
3,16.180322,0.000297,0.399683,0.791782,0.330572,0.127251,246.338595,5.020474,7.410957,0.172811,1.734462,0.588260,0.260439,0.249749
4,20.490799,0.000520,0.093854,0.370457,0.181196,0.117914,39.434356,8.012659,1.729734,0.872576,2.888513,0.657149,0.289042,0.854937

In [17]:
all_results = pd.concat([evaluation_metrics, parameters], axis=1)
all_results.head()

,NSE on Flow,NSE on Soil,KGE on Flow,KGE on Soil,SeasonTrans of Soil dry2wet_start,SeasonTrans of Soil dry2wet_end,SeasonTrans of Soil wet2dry_start,SeasonTrans of Soil wet2dry_end,bb,satdk,...,smcmax,wltsmc,max_gw_storage,Cgw,epon,K_nash,refkdt,trigger_z_m,alpha_fc,K_lf
run_id,,,,,,,,,,,,,,,,,,,,,
0,-30.568738,-12.342179,-3.686758,-0.553540,72.749674,108.922218,66.649729,130.712276,4.027623,0.000351,...,0.843931,0.137223,68.195614,1.527645,3.546989,0.822001,0.193795,0.477602,0.257059,0.653631
1,-83.056301,-0.374212,-7.333551,0.160021,72.749565,115.994626,66.146897,161.431462,9.320904,0.000271,...,0.239038,0.085257,33.573071,6.585309,0.265659,0.977133,2.459490,0.603067,0.223187,0.455743
2,-70.208145,-3.862425,-6.695484,-0.018434,72.844123,113.131792,65.334942,141.854032,2.406037,0.000084,...,0.365838,0.019829,106.207128,8.361439,3.151870,0.598343,3.822082,0.444100,0.305219,0.790704
3,-15.989324,-1.395726,-2.430271,0.122937,72.749565,121.328924,65.628257,166.074534,16.180322,0.000297,...,0.330572,0.127251,246.338595,5.020474,7.410957,0.172811,1.734462,0.588260,0.260439,0.249749
4,-202.755735,0.009241,-12.687862,0.062920,95.348474,140.208906,51.937005,104.204529,20.490799,0.000520,...,0.181196,0.117914,39.434356,8.012659,1.729734,0.872576,2.888513,0.657149,0.289042,0.854937

In [18]:
target_params = ["max_gw_storage", "Cgw", "epon"]
eval_metrics_names = ["NSE on Flow", "NSE on Soil", "KGE on Flow", "KGE on Soil"]

In [25]:
def plot_parameter_dotty(all_results, target_params, eval_metrics, output_path):
    nparas = len(target_params)

    for target_eval in eval_metrics:
        f, axes = plt.subplots(
            nparas, 1, figsize=(7, 7), constrained_layout=True
        )

        for i, target_para in enumerate(target_params):
            ax = axes[i]
            ax.scatter(
                all_results[target_para],
                all_results[target_eval],
                alpha=0.5,
            )
            ax.tick_params(axis="both", which="major", labelsize=16)
            ax.set_xlabel(target_para, fontsize=16)
            ax.set_ylabel(target_eval, fontsize=16)
            ax.set_ylim([-1, 1])

        save_path = os.path.join(output_path, f"param_dotty_{target_eval}.png")
        f.savefig(save_path, dpi=600)
        plt.close(f)

In [26]:
plot_parameter_dotty(all_results, target_params, eval_metrics_names, output_path)